version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: hexagonal-blog
    ports:
      - 27017:27017

  server:
    container_name: hexagonal_blog
    build: .
    command: npm run start
    depends_on:
      - 'mongo'
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/app